-- Fresh Listings production PostgreSQL baseline.
--
-- Apply this file with the PostgreSQL migration command after DATABASE_URL is
-- provisioned. PostgreSQL is the canonical production data store.
-- Never paste this into production without a backup and a staging run first.

CREATE TABLE IF NOT EXISTS users (
  id text PRIMARY KEY,
  auth_subject text NOT NULL UNIQUE,
  email text NOT NULL,
  display_name text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_postings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  external_id text NOT NULL,
  title text NOT NULL,
  company text NOT NULL,
  location text NOT NULL DEFAULT 'Location not listed',
  source text NOT NULL,
  direct_url text NOT NULL,
  apply_url text,
  description text NOT NULL DEFAULT '',
  posted_at text,
  remote_status text,
  experience text,
  salary text,
  skills_json text NOT NULL DEFAULT '[]',
  fit_score integer CHECK (fit_score IS NULL OR fit_score BETWEEN 0 AND 100),
  fit_summary text,
  skill_gaps text,
  portfolio_projects text,
  search_query text NOT NULL DEFAULT '',
  captured_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  synced_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (owner_user_id, external_id)
);

CREATE INDEX IF NOT EXISTS job_postings_owner_created_idx
  ON job_postings (owner_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS job_postings_owner_source_idx
  ON job_postings (owner_user_id, source, created_at DESC);

CREATE TABLE IF NOT EXISTS scrape_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider text NOT NULL,
  keywords text NOT NULL,
  location text NOT NULL,
  time_window text NOT NULL,
  result_count integer NOT NULL DEFAULT 0,
  status text NOT NULL,
  error text,
  idempotency_key text,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS scrape_runs_owner_idempotency_idx
  ON scrape_runs (owner_user_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS user_settings (
  owner_user_id text PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  email text NOT NULL,
  keywords_json text NOT NULL DEFAULT '["Software engineer"]',
  locations_json text NOT NULL DEFAULT '["United States"]',
  selected_sources_json text NOT NULL DEFAULT '["google_jobs","greenhouse"]',
  digest_enabled integer NOT NULL DEFAULT 0,
  digest_hour text NOT NULL DEFAULT '08:00',
  google_account_email text,
  google_drive_folder_id text,
  spreadsheet_id text,
  google_refresh_token text,
  google_access_token text,
  google_access_expires_at bigint,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Reserved for integrations that outgrow the current Google/Telegram columns,
-- the API can migrate tokens here without changing the user/job tables.
CREATE TABLE IF NOT EXISTS user_integrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider text NOT NULL,
  provider_account_id text,
  provider_account_email text,
  encrypted_refresh_token text,
  encrypted_access_token text,
  access_token_expires_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (owner_user_id, provider)
);

CREATE TABLE IF NOT EXISTS oauth_states (
  state text PRIMARY KEY,
  owner_user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS telegram_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id text NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  chat_id text NOT NULL UNIQUE,
  username text,
  display_name text,
  notifications_enabled integer NOT NULL DEFAULT 1,
  linked_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS telegram_link_tokens (
  token text PRIMARY KEY,
  owner_user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at bigint NOT NULL,
  used_at bigint
);

CREATE TABLE IF NOT EXISTS outbox_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id text REFERENCES users(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  available_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS outbox_events_pending_idx
  ON outbox_events (available_at, created_at)
  WHERE published_at IS NULL;

CREATE TABLE IF NOT EXISTS daily_metrics (
  owner_user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  metric_day date NOT NULL,
  jobs_searched integer NOT NULL DEFAULT 0,
  jobs_saved integer NOT NULL DEFAULT 0,
  search_runs integer NOT NULL DEFAULT 0,
  PRIMARY KEY (owner_user_id, metric_day)
);
